### ISSUE TITLE
Some bug with "Detail: Unauthenticated   Invalid bearer token provided. Detail: Unauthenticated"

### ISSUE THREAD

**Issue by YuriyGavrilov** [voltrondata/flight-sql-server-example#11]
Dbeaver log:

cfjd.org.apache.arrow.flight.FlightRuntimeException: UNAUTHENTICATED: Invalid bearer token provided. Detail: Unauthenticated
  cfjd.org.apache.arrow.flight.FlightRuntimeException: UNAUTHENTICATED: Invalid bearer token provided. Detail: Unauthenticated
  Invalid bearer token provided. Detail: Unauthenticated

Tableau log:

Unable to complete action
Bad Connection: Tableau could not connect to the data source.
Error Code: FAB9A2C5
cfjd.org.apache.arrow.flight.FlightRuntimeException: UNAUTHENTICATED: Invalid bearer token provided. Detail: Unauthenticated
Generic JDBC connection error
cfjd.org.apache.arrow.flight.FlightRuntimeException: UNAUTHENTICATED: Invalid bearer token provided. Detail: Unauthenticated

Context: 
After docker run I can properly get access to dbever. but when I just try to connect with tableau it show UNAUTHENTICATION issue . After I go back to dbever and it shows same UNAUTHENTICATION issue till I restart docker. 

This is terminal docker log.  

```
2023-11-06 22:06:30 Client running SQL command:     
2023-11-06 22:06:30 SELECT * FROM "customer";  # Dbeaver select 
2023-11-06 22:06:30 
2023-11-06 22:06:35 Client running SQL command: 
2023-11-06 22:06:35 SELECT VERSION();  # dbeaver version select 
2023-11-06 22:06:35 
2023-11-06 22:07:17 Bearer Token verification failed with exception: failed to verify signature: VerifyFinal failed   #Tableau try to access 
2023-11-06 22:07:17 Client running SQL command: 
2023-11-06 22:07:17 SELECT 1;
2023-11-06 22:07:17 
```

It happens when I try to connect from Tableau with "Mysql" dialect and Postgres dialect. It shows nothing with SQL92. 
<img width="599" alt="Снимок экрана 2023-11-06 в 22 10 09" src="https://github.com/voltrondata/flight-sql-server-example/assets/44679014/a688efb9-7e0c-42d7-bb27-426f0b746782">

**Comment by prmoore77** [comment]
hi @YuriyGavrilov - the JDBC client can cache tokens - so it may likely be trying to use a token that was generated for localhost before you ran in Docker.

I would suggest using a different value for the `FLIGHT_PASSWORD` environment variable when you start Docker - that should force the client to invalidate the cache, and you should get a new token.  Could you try that, and let me know if it works?

**Comment by prmoore77** [comment]
Also - I used the PostgreSQL dialect when I tested on my end - it seemed to work well.  I did not test MySQL - as DuckDB seems to use more of a PostgreSQL dialect...

**Comment by prmoore77** [comment]
I found that adding `&token=null` to the jdbc URL in Tableau helped.  It seems to force Tableau to grab a fresh auth token using username/password....

**Comment by prmoore77** [comment]
Thanks for testing...  It seems we need to overhaul either the server's auth code, or allow a way to force a token refresh in the JDBC driver with an argument.  I'll research this more and try to find a good strategy...

**Comment by prmoore77** [comment]
@YuriyGavrilov - I believe I've fixed the issue.  Could you validate?

**Comment by YuriyGavrilov** [comment]
@prmoore77 I've also made some changes in arrow. May be you should know it to make some adoption. https://github.com/apache/arrow/issues/38253 (https://github.com/apache/arrow/issues/38737 - this PR)  or may be need to add different issue it but anyway I put it here may be nothing needs to do)

**Comment by prmoore77** [comment]
hi @YuriyGavrilov - unfortunately, my Tableau trial license expired - so I'm unable to test things with it now.  Before it expired, I believe I had it all working with the Arrow Flight SQL JDBC driver version: `14.0.1`, however.  I chose the PostgreSQL dialect - and I was able to view tables, etc. - but I didn't capture screenshots, unfortunately.

I wish I could help more, but it may take me a while to get a Tableau license...

**Comment by YuriyGavrilov** [comment]
it't ok. @prmoore77 

for the 14.0.1 I get this message. 

<img width="913" alt="Снимок экрана 2023-12-05 в 00 14 56" src="https://github.com/voltrondata/flight-sql-server-example/assets/44679014/debe28a0-4414-4cfc-a56e-63f22ad933f4">

<img width="311" alt="Снимок экрана 2023-12-05 в 00 16 38" src="https://github.com/voltrondata/flight-sql-server-example/assets/44679014/e700a69f-85d8-4c2d-9b82-018aa35bd66e">

I ve download it with this artifact:

```
<dependency>
    <groupId>org.apache.arrow</groupId>
    <artifactId>flight-sql-jdbc-driver</artifactId>
    <version>14.0.1</version>
</dependency>

```
it works fine in dbeaver.

**Comment by YuriyGavrilov** [comment]
I use this doc to locate it https://help.tableau.com/current/pro/desktop/en-us/examples_otherdatabases_jdbc.htm?_gl=1*13o39fp*_ga*NjU2NzcyNDc5LjE3MDA5NDA1MDc.*_ga_8YLN0SNXVS*MTcwMTcyNTgzOS41LjEuMTcwMTcyNTg3MS4wLjAuMA..

```
Specify the right JDBC driver
JDBC drivers are self-contained .jar files. Place the .jar files in the folder for your operating system. (You need to create the folder if it doesn't already exist.)

Windows: C:\Program Files\Tableau\Drivers
Mac: ~/Library/Tableau/Drivers
Linux: /opt/tableau/tableau_driver/jdbc
```

**Comment by prmoore77** [comment]
Oh - also, I think you can now remove the `&token=null` from the JDBC url (since we updated the code)...

**Comment by YuriyGavrilov** [comment]
> Did you remove other versions of the driver? Maybe there can only be one version in the folder...

Yep, sure

**Comment by YuriyGavrilov** [comment]
@prmoore77 Finally I run flight sql, but with kamu-cli project ... to be sure that tableau is working. 

<img width="1462" alt="Снимок экрана 2023-12-05 в 23 05 56" src="https://github.com/voltrondata/flight-sql-server-example/assets/44679014/b62c5d23-e3fb-4b79-ac0b-baf0764ff402">

tables showed properly and with sql92 dialect. (ok, 98% properly :), some sql errors still exist 

based on this example https://github.com/kamu-data/kamu-cli/tree/master/examples/trading
and run this 

```
cd trading
kamu init
kamu add . --recursive
kamu pull --all
kamu sql server --flight-sql
```

Connect using URL: jdbc:arrow-flight-sql://127.0.0.1:10000?useEncryption=false
Use 'kamu' as login and password

**Comment by prmoore77** [comment]
@YuriyGavrilov - Great news!  Did you have to change any of the Flight SQL server code, etc?  Is there a fix I need to make?  Thanks!

**Comment by prmoore77** [comment]
By the way - that `kamu` tool looks very cool!  Thanks for sharing.

**Comment by prmoore77** [comment]
hi @YuriyGavrilov - I got a Tableau license - and tested with the default TPC-H database that comes with the docker image for this example Flight SQL server.

I started the Flight SQL server with:
```
docker run --name flight-sql \
           --detach \
           --rm \
           --tty \
           --init \
           --publish 31337:31337 \
           --env FLIGHT_PASSWORD="flight_password" \
           --env PRINT_QUERIES="1" \
           --pull missing \
           voltrondata/flight-sql:latest
```

I am using the [14.0.2 JDBC driver version](https://repo1.maven.org/maven2/org/apache/arrow/flight-sql-jdbc-driver/14.0.2/flight-sql-jdbc-driver-14.0.2.jar) - with JDBC url: `jdbc:arrow-flight-sql://localhost:31337?useEncryption=true&disableCertificateVerification=true`

I choose: `PostgreSQL` dialect - and it seems that all is working:
<img width="1840" alt="Screenshot 2023-12-20 at 11 32 11 AM" src="https://github.com/voltrondata/flight-sql-server-example/assets/20807693/6103c1fb-2767-4b58-bd3c-4def10b7f8e9">

Can you verify on your end?

**Comment by YuriyGavrilov** [comment]
Yep, sure I will. Are use Mac OS or Win?

**Comment by prmoore77** [comment]
Mac OS

On Dec 20, 2023, at 3:21 PM, Yuriy Gavrilov ***@***.***> wrote:

﻿

Yep, sure I will. Are use Mac OS or Win?
